// <auto-generated />
namespace PatientenAkte.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class nextMig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nextMig));
        
        string IMigrationMetadata.Id
        {
            get { return "202102102002029_nextMig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
